version: '3'
services:
  aqoap_mongo_db:
    platform: linux/x86_64
    image: mongo:4.4.6
    container_name: aqoap_mongo
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
    hostname: aqoap_mongo
    ports:
      - "0.0.0.0:27777:27017" # Bind to all available IP addresses
    networks:
      - aqoap_network

  aqoap_dashboard:
    platform: linux/x86_64
    image: aqoap-dashboard:latest
    container_name: aqoap_dashboard
    hostname: aqoap_dashboard
    ports:
      - "0.0.0.0:8888:8080" # Bind to all available IP addresses
    networks:
      - aqoap_network

volumes:
  db-data:
  mongo-config:

networks:
  aqoap_network:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "10.22.0.0/24"
                gateway: "10.22.0.1"

